# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)
print()
print(type(arr))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]

<class 'numpy.ndarray'>


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [9]:
l1 = list(map(float,input().split()))[:5]
l2 = list(map(float,input().split()))[:5]
arr1 = np.array(l1)
arr2 = np.array(l2)
arr3 = np.concatenate((arr1,arr2))
print()
print(arr3)  # Concatinating arr1 and arr2
print()
arr1 = np.sort(arr1)
arr2 = np.sort(arr2)
print(arr1)     # Printing the sorted array 1
print()
print(arr2)    # Printing the sorted array 2

1 2 3 4
5 6 7 8

[1. 2. 3. 4. 5. 6. 7. 8.]

[1. 2. 3. 4.]

[5. 6. 7. 8.]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [10]:
arr1 = np.arange(12)
print(arr1)
print(np.ndim(arr1))
print(np.size(arr1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
12


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [14]:
print(arr1.shape)
arr1[:,np.newaxis,np.newaxis].shape

(12,)


(12, 1, 1)

# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.

In [8]:
a = np.arange(4)
b = np.arange(5,9)
print(a)
print()
print(b)
print()
print('Horizontal stack',np.hstack((a,b)))
print()
print('Vertical Stack',np.vstack((a,b)))

[0 1 2 3]

[5 6 7 8]

Horizontal stack [0 1 2 3 5 6 7 8]

Vertical Stack [[0 1 2 3]
 [5 6 7 8]]


# Questions 6:
How to get unique items and counts of unique items?

In [6]:
arr = np.array([1,2,3,4,5,6,1,2,3])
print(arr)
print()
arr2 = np.unique(arr)
print('Unique values of array1:',arr2)
print()
print('Number of unique values',np.size(arr2))

[1 2 3 4 5 6 1 2 3]

Unique values of array1: [1 2 3 4 5 6]

Number of unique values 6
